apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gosheap.fullname" . }}
  labels:
    {{- include "gosheap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gosheap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gosheap.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: MONGODB_URL
            value: mongodb://experiment-mongodb:27017/gosheap
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: port-01
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
