{{- $fullName := include "gosheap.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  annotations:
    kubernets.io/ingress.class: "nginx"
  labels:
    {{- include "gosheap.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ $fullName }}.stage.piaas.it-k8s.in.pan-net.eu
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-service
              servicePort: {{ $svcPort }}
