apiVersion: v1
kind: Service
metadata:
  name: {{ include "gosheap.fullname" . }}-service
  labels:
    {{- include "gosheap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: port-01
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "gosheap.selectorLabels" . | nindent 4 }}
